services:
	mariadb:
		image: mariadb:11
		container_name: veille-mariadb
		restart: unless-stopped
		environment:
			- MARIADB_ROOT_PASSWORD=root
			- MARIADB_DATABASE=veille
			- MARIADB_USER=app
			- MARIADB_PASSWORD=app
		ports:
			- "3306:3306"
		volumes:
			- mariadb_data:/var/lib/mysql

volumes:
	mariadb_data:
		driver: local
